[package]
name = "katana"
description = "A fast and accurate rule-based sentence segmentation tool for Rust. A port from Louie Mullie's Scalpel."
version = "1.0.0"
authors = ["McFreely <paulmcfreely@gmail.com>"]

[dependencies]
regex = "0.1.8"
